# Generated by Django 2.2.2 on 2020-06-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('url', models.URLField()),
                ('show_order', models.SmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['show_order'],
            },
        ),
    ]
